server:
  port: 8080
  servlet:
    context-path: /generator

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://60.205.212.196:3306/cloud_disk?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: disk
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/

mybatis:
  mapperLocations: classpath:mapper/**/*.xml

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#指定数据库
renren:
  database: mysql
